Search.appendIndex(
    [
                {
            "fqsen": "\\dto\\User",
            "name": "User",
            "summary": "Class\u0020User",
            "url": "classes/dto-User.html"
        },                {
            "fqsen": "\\dto\\User\u003A\u003Asign_up\u0028\u0029",
            "name": "sign_up",
            "summary": "Method\u0020sign_up",
            "url": "classes/dto-User.html#method_sign_up"
        },                {
            "fqsen": "\\dto\\User\u003A\u003Asign_in\u0028\u0029",
            "name": "sign_in",
            "summary": "Method\u0020sign_in",
            "url": "classes/dto-User.html#method_sign_in"
        },                {
            "fqsen": "\\dto\\User\u003A\u003Aget_birthdate\u0028\u0029",
            "name": "get_birthdate",
            "summary": "Method\u0020get_birthdate",
            "url": "classes/dto-User.html#method_get_birthdate"
        },                {
            "fqsen": "\\dto\\User\u003A\u003Achange_username\u0028\u0029",
            "name": "change_username",
            "summary": "Method\u0020change_name",
            "url": "classes/dto-User.html#method_change_username"
        },                {
            "fqsen": "\\exception\\DataAlreadyExistsException",
            "name": "DataAlreadyExistsException",
            "summary": "Class\u0020DataAlreadyExistsException",
            "url": "classes/exception-DataAlreadyExistsException.html"
        },                {
            "fqsen": "\\exception\\DataAlreadyExistsException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DataAlreadyExistsException\u0020constructor.",
            "url": "classes/exception-DataAlreadyExistsException.html#method___construct"
        },                {
            "fqsen": "\\exception\\DataNotFoundException",
            "name": "DataNotFoundException",
            "summary": "Class\u0020DataNotFoundException",
            "url": "classes/exception-DataNotFoundException.html"
        },                {
            "fqsen": "\\exception\\DataNotFoundException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DataNotFoundException\u0020constructor.",
            "url": "classes/exception-DataNotFoundException.html#method___construct"
        },                {
            "fqsen": "\\exception\\UsernameAlreadyExistsException",
            "name": "UsernameAlreadyExistsException",
            "summary": "Class\u0020UsernameAlreadyExistsException",
            "url": "classes/exception-UsernameAlreadyExistsException.html"
        },                {
            "fqsen": "\\exception\\UsernameAlreadyExistsException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "UsernameAlreadyExistsException\u0020constructor.",
            "url": "classes/exception-UsernameAlreadyExistsException.html#method___construct"
        },                {
            "fqsen": "\\exception\\UserNotFoundException",
            "name": "UserNotFoundException",
            "summary": "Class\u0020UserNotFoundException",
            "url": "classes/exception-UserNotFoundException.html"
        },                {
            "fqsen": "\\exception\\UserNotFoundException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "UserNotFoundException\u0020constructor.",
            "url": "classes/exception-UserNotFoundException.html#method___construct"
        },                {
            "fqsen": "\\exception\\WrongPasswordException",
            "name": "WrongPasswordException",
            "summary": "Class\u0020WrongPasswordException",
            "url": "classes/exception-WrongPasswordException.html"
        },                {
            "fqsen": "\\exception\\WrongPasswordException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "WrongPasswordException\u0020constructor.",
            "url": "classes/exception-WrongPasswordException.html#method___construct"
        },                {
            "fqsen": "\\print_exception\u0028\u0029",
            "name": "print_exception",
            "summary": "Method\u0020print_exception",
            "url": "namespaces/default.html#function_print_exception"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\dto",
            "name": "dto",
            "summary": "",
            "url": "namespaces/dto.html"
        },                {
            "fqsen": "\\exception",
            "name": "exception",
            "summary": "",
            "url": "namespaces/exception.html"
        }            ]
);
